const $=s=>document.querySelector(s);const nav=$('#nav');$('#menuBtn')?.addEventListener('click',()=>nav.classList.toggle('open'));
async function loadJSON(path,fallback){try{const r=await fetch(path);if(!r.ok)throw new Error('no');return await r.json()}catch(e){return fallback}}
const ideasFallback=[{pair:'XAU/USD',type:'SELL',entry:'4040–4050',sl:'4097',tp:'4000 / 3975',risk:'Mediu',note:'Așteaptă confirmare M5/M15 înainte de intrare.'},{pair:'EUR/USD',type:'BUY',entry:'1.0870',sl:'1.0820',tp:'1.0950',risk:'Scăzut',note:'Valabil doar dacă USD slăbește după știri.'},{pair:'GBP/USD',type:'WATCH',entry:'1.2700',sl:'-',tp:'-',risk:'Observare',note:'Așteptăm break clar peste rezistență.'}];
const reportsFallback=[{symbol:'XAU/USD',price:'4,040.52',change:'-65.19 (-1.59%)',dir:'red'},{symbol:'XAG/USD',price:'57.762',change:'-2.20 (-3.66%)',dir:'red'},{symbol:'EUR/USD',price:'1.08956',change:'+0.00123 (+0.11%)',dir:'green'},{symbol:'GBP/USD',price:'1.27034',change:'+0.00215 (+0.17%)',dir:'green'}];
function cardIdea(x){return `<article class="glass market-card"><h3>${x.pair}<span>${x.type}</span></h3><p><b>Intrare:</b> ${x.entry}<br><b>SL:</b> ${x.sl}<br><b>TP:</b> ${x.tp}<br><b>Risc:</b> ${x.risk}</p><p>${x.note}</p></article>`}
function cardReport(x){return `<article class="glass market-card"><h3>${x.symbol}</h3><p class="price">${x.price}</p><p class="${x.dir}">${x.change}</p><a class="outline" href="#">Analiză săptămânală</a></article>`}
async function render(){const ideas=await loadJSON('data/ideas.json',ideasFallback);$('#ideasGrid').innerHTML=ideas.map(cardIdea).join('');const reports=await loadJSON('data/reports.json',reportsFallback);$('#reportsGrid').innerHTML=reports.map(cardReport).join('')}render();
$('#unlockIdeas')?.addEventListener('click',()=>{const pass=$('#memberPass').value.trim();if(pass==='treidingsb'){document.querySelector('.access-panel').classList.add('hidden');$('#ideasContent').classList.remove('hidden');$('#ideasContent').classList.add('reveal');}else{$('#loginMsg').textContent='Parolă greșită. Încearcă din nou.'}});
$('#subscribeForm')?.addEventListener('submit',async(e)=>{e.preventDefault();$('#subscribeMsg').textContent='Pentru trimitere reală conectăm api/send-email.js cu Resend.'});
